@startwbs ONI-LINK
title
WBS
endtitle
* ONI-LINK
** 環境準備
*** サーバーの構築
**** ソケットの作成
**** ユーザーの入力を受け取って更新する
**** 受信したデータを記憶するリストを作る
*** クライアント接続
**** サーバーへの接続要求送信
**** サーバーからのゲーム状態受信スレッドの開始
**** ゲーム開始シグナルの待機
** ゲームの仕様
*** 鬼と逃げ役の割り振り
**** プレイヤーリストの作成
**** ランダム割当て
*** 当たり判定
**** 鬼と逃げる人が衝突したときの処理
**** 障害物にぶつかった場合の処理
*** タイマー処理
**** 制限時間を設定
**** 制限時間を過ぎたときの処理
*** マップ描画
**** 画像を用意
**** 背景に画像を張り付ける
**** 障害物配置
*** キャラクター描画
**** 画像を用意
**** 役割によって画像の変更
*** プレイヤー操作
**** サイズ調整
**** ボタン割当て
**** 速度を調整する
** サーバーへの送信
*** プレイヤー位置の共有
**** 全員の座標を受信
**** 各プレイヤーを描画
*** ゲーム結果の同期
**** 確保or時間切れを判定
**** 勝敗結果を表示
@endwbs