@startwbs ONI-LINK
title
WBS
endtitle
* ONI-LINK
** 画面遷移
*** タイトル画面
**** 背景画像表示
**** ボタンの表示
**** 名前やIPの入力欄作成
*** ロビー画面
**** 背景画像表示
**** 待機人数の表示
*** ゲーム終了画面
**** ボタンの表示
**** もう一度の処理の作成
** ユーザビリティ向上
*** プレイヤー名の表示
**** 名前を画面に表示させる
**** プレイヤーと一緒に移動させる
*** 操作確認のヘルプの追加
**** ヘルプボタン作成
**** メッセージボックス表示
** 追加機能
*** アイテムの実装
**** 画像を表示させる
**** プレイヤーとアイテムが衝突したときの処理
*** 一人でも遊べるようにする
**** 一人で遊ぶかオンラインか選択する
**** 画面遷移
*** 脱出機能を追加したモード
**** 画像の表示
**** 出口の処理
@endwbs